youcan-shop/youcan-ui

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Dropdown/Dropdown.vue
packages/vue3/src/components/Dropdown/DropdownList.vue

[YSHOP2-1057](https://youcanshop.atlassian.net/browse/YSHOP2-1057)
[YSHOP2-1057]: https://youcanshop.atlassian.net/browse/YSHOP2-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: Dropdown isn’t aware of edges

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Alert/Alert.vue
packages/vue3/src/components/Toast/Toast.vue
packages/vue3/src/components/Toast/types.ts
packages/vue3/src/components/index.ts

[YSHOP2-1059](https://youcanshop.atlassian.net/browse/YSHOP2-1059)
[YSHOP2-1059]: https://youcanshop.atlassian.net/browse/YSHOP2-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1059: Create Toast component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Button/_BaseButton.vue
packages/vue3/src/components/Modal/Modal.vue
packages/vue3/src/components/Overlay/Overlay.vue

[YSHOP2-1060](https://youcanshop.atlassian.net/browse/YSHOP2-1060)
[YSHOP2-1060]: https://youcanshop.atlassian.net/browse/YSHOP2-1060?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1060: Create Modal component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/DateInput/DateInput.vue
packages/vue3/src/components/DateInput/DatePicker.vue

[YSHOP2-1104](https://youcanshop.atlassian.net/browse/YSHOP2-1104)
Check this resolved issues please
[YSHOP2-1104]: https://youcanshop.atlassian.net/browse/YSHOP2-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1104: DatePicker > Fix date range issue

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Modal/Modal.vue

[YSHOP2-1102](https://youcanshop.atlassian.net/browse/YSHOP2-1102)
[YSHOP2-1102]: https://youcanshop.atlassian.net/browse/YSHOP2-1102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1102: Fix modal bugs

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/PaginationBar/PaginationBar.vue

[YSHOP2-1122](https://youcanshop.atlassian.net/browse/YSHOP2-1122)
[YSHOP2-1122]: https://youcanshop.atlassian.net/browse/YSHOP2-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1122: Add hide-per-page prop to PaginationBar

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Spinner/Spinner.vue
packages/vue3/src/components/Spinner/types.ts
packages/vue3/src/components/index.ts

[YSHOP2-1129](https://youcanshop.atlassian.net/browse/YSHOP2-1129)
[YSHOP2-1129]: https://youcanshop.atlassian.net/browse/YSHOP2-1129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1129 : Added a spinner component with a label

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Popover/Popover.vue
packages/vue3/src/components/Popover/types.ts
packages/vue3/src/components/index.ts

[YSHOP2-1074](https://youcanshop.atlassian.net/browse/YSHOP2-1074)
[YSHOP2-1074]: https://youcanshop.atlassian.net/browse/YSHOP2-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1074: Create Popover (Callout) component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Radio/Radio.vue

Dark: Fixed radio groupe cursor style

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Sidebar/Sidebar.vue
packages/vue3/src/components/Sidebar/SidebarItem.vue
packages/vue3/src/components/Sidebar/SidebarSubitem.vue

[YSHOP2-1165](https://youcanshop.atlassian.net/browse/YSHOP2-1165)
[YSHOP2-1165]: https://youcanshop.atlassian.net/browse/YSHOP2-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1165: fix sidebar issue

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Alert/Alert.vue
packages/vue3/src/components/Alert/types.ts

[YSHOP2-1178](https://youcanshop.atlassian.net/browse/YSHOP2-1178)
* Go to App.vue and check Alart types `'warning' | 'success' | 'info' | 'error'` if all is good
[YSHOP2-1178]: https://youcanshop.atlassian.net/browse/YSHOP2-1178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1178: Alert > Add error variant

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/MultiSwitch/MultiSwitch.vue
packages/vue3/src/components/MultiSwitch/SwitchButton.vue
packages/vue3/src/components/MultiSwitch/types.ts

[YSHOP2-1197](https://youcanshop.atlassian.net/browse/YSHOP2-1197)
[YSHOP2-1197]: https://youcanshop.atlassian.net/browse/YSHOP2-1197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1197: Reduce amount of props needed for MultiSwitch

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Popover/Popover.vue
packages/vue3/src/components/Tooltip/Tooltip.vue
packages/vue3/src/components/Tooltip/utils.ts

[YSHOP2-1198](https://youcanshop.atlassian.net/browse/YSHOP2-1198)
[YSHOP2-1198]: https://youcanshop.atlassian.net/browse/YSHOP2-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1198: Feature Callout > Add edge awareness

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Upload/MediaInput.vue

[YSHOP2-1212](https://youcanshop.atlassian.net/browse/YSHOP2-1212)
[YSHOP2-1212]: https://youcanshop.atlassian.net/browse/YSHOP2-1212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1212: Fixed MediaInput sublabel not required

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/ResourcePicker/ResourcePicker.vue

DARK: fix ResourcePicker resources reactive bug

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/ResourcePicker/Internal/Resource.vue
packages/vue3/src/components/ResourcePicker/ResourcePicker.vue

DARK: improve resource picker styles

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Dropdown/Dropdown.vue
packages/vue3/src/components/Dropdown/DropdownList.vue
packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
packages/vue3/src/components/Dropdown/helpers.ts

[YSHOP2-1217](https://youcanshop.atlassian.net/browse/YSHOP2-1217)
[YSHOP2-1217]: https://youcanshop.atlassian.net/browse/YSHOP2-1217?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1217: Add fixes based on Feedback meeting

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Divider/Divider.vue
packages/vue3/src/components/Divider/types.ts

[YSHOP2-1221](https://youcanshop.atlassian.net/browse/YSHOP2-1221)
[YSHOP2-1221]: https://youcanshop.atlassian.net/browse/YSHOP2-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1221: Added thickness prop to divider

---

packages/vue3/src/components/ResourcePicker/ResourcePicker.vue
packages/vue3/src/components/ResourcePicker/types.ts

DARK: add searchPlaceholder as prop

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Divider/Divider.vue

[YSHOP2-1213](https://youcanshop.atlassian.net/browse/YSHOP2-1213)
[YSHOP2-1213]: https://youcanshop.atlassian.net/browse/YSHOP2-1213?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1213: Fixed divider vertical orientation

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Divider/Divider.vue

[YSHOP2-1214](https://youcanshop.atlassian.net/browse/YSHOP2-1214)
[YSHOP2-1214]: https://youcanshop.atlassian.net/browse/YSHOP2-1214?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1214: Added margin to the divider

---

packages/vue3/src/components/Dropdown/types.ts

Fixed dropdown types export

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/ResourcePicker/ResourcePicker.vue

DARK: dark-make-resourcePicker-variants-POJOs

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Input/Input.vue

[YSHOP2-1247](https://youcanshop.atlassian.net/browse/YSHOP2-1247)
[YSHOP2-1247]: https://youcanshop.atlassian.net/browse/YSHOP2-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1247: Input > Add Show/Hide if Input type is password

---

CONTRIBUTING.md

[YSHOP2-1245](https://youcanshop.atlassian.net/browse/YSHOP2-1245)
[YSHOP2-1245]: https://youcanshop.atlassian.net/browse/YSHOP2-1245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update CONTRIBUTING.md to include step to run build

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Alert/Alert.vue
packages/vue3/src/components/Alert/types.ts
packages/vue3/src/components/Badge/Badge.vue
packages/vue3/src/components/Badge/types.ts
packages/vue3/src/components/Checkbox/Checkbox.vue
packages/vue3/src/components/Checkbox/types.ts

Added custom props type for alert-badge-checkbox

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Button/PrimaryButton.vue
packages/vue3/src/components/Button/PrimaryDestructiveButton.vue
packages/vue3/src/components/Button/SecondaryButton.vue
packages/vue3/src/components/Button/SecondaryDestructiveButton.vue
packages/vue3/src/components/Button/TertiaryButton.vue
packages/vue3/src/components/Button/_BaseButton.vue
packages/vue3/src/components/Button/types.ts

Added custom type for buttons props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Color/ColorInput.vue
packages/vue3/src/components/Color/ColorPicker.vue
packages/vue3/src/components/Color/Internal/Alpha.vue
packages/vue3/src/components/Color/Internal/Backdrop.vue
packages/vue3/src/components/Color/Internal/Hue.vue
packages/vue3/src/components/Color/Internal/Override.vue
packages/vue3/src/components/Color/Internal/Saturation.vue
packages/vue3/src/components/Color/Internal/Swatches.vue
packages/vue3/src/components/Color/Internal/types.ts
packages/vue3/src/components/Color/types.ts

Added custom props for color component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/DateInput/DateInput.vue
packages/vue3/src/components/DateInput/DatePicker.vue
packages/vue3/src/components/DateInput/Internal/Day.vue
packages/vue3/src/components/DateInput/Internal/MonthSwitcher.vue
packages/vue3/src/components/DateInput/Internal/types.ts
packages/vue3/src/components/DateInput/types.ts
packages/vue3/src/components/Divider/Divider.vue
packages/vue3/src/components/Divider/types.ts

Added custom props for divider and dateInput

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Draggable/Draggable.vue
packages/vue3/src/components/Draggable/DraggableItem.vue
packages/vue3/src/components/Draggable/types.ts
packages/vue3/src/components/Dropdown/Dropdown.vue
packages/vue3/src/components/Dropdown/DropdownList.vue
packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
packages/vue3/src/components/Dropdown/types.ts

Added custom types for components props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Increment/Increment.vue
packages/vue3/src/components/Increment/types.ts
packages/vue3/src/components/Input/Input.vue
packages/vue3/src/components/Input/prefixes/DropdownPrefix.vue
packages/vue3/src/components/Input/types.ts
packages/vue3/src/components/Loading/Loading.vue
packages/vue3/src/components/Loading/types.ts

Added custom types for increment input loading props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Modal/Modal.vue
packages/vue3/src/components/Modal/types.ts
packages/vue3/src/components/MultiSwitch/MultiSwitch.vue
packages/vue3/src/components/MultiSwitch/SwitchButton.vue
packages/vue3/src/components/MultiSwitch/types.ts
packages/vue3/src/components/PaginationBar/Internal/NavigationButton.vue
packages/vue3/src/components/PaginationBar/PaginationBar.vue
packages/vue3/src/components/PaginationBar/types.ts

Added custom types for modal multiswitch and pagination bar props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/RadioList/RadioList.vue
packages/vue3/src/components/RadioList/types.ts
packages/vue3/src/components/Rating/Rating.vue
packages/vue3/src/components/Rating/RatingInput.vue
packages/vue3/src/components/Rating/types.ts
packages/vue3/src/components/Search/Internal/SearchResult.vue
packages/vue3/src/components/Search/SearchInput.vue
packages/vue3/src/components/Search/types.ts

Added custom types for radioList rating and search props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/SettingsNav/SettingsNavItem.vue
packages/vue3/src/components/SettingsNav/types.ts
packages/vue3/src/components/Sidebar/Sidebar.vue
packages/vue3/src/components/Sidebar/SidebarItem.vue
packages/vue3/src/components/Sidebar/SidebarSubitem.vue
packages/vue3/src/components/Sidebar/types.ts
packages/vue3/src/components/Skeleton/Skeleton.vue
packages/vue3/src/components/Skeleton/types.ts

Added custom types for SettingsNav Sidebar and Skeleton props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Slider/Slider.vue
packages/vue3/src/components/Slider/types.ts
packages/vue3/src/components/Spinner/Spinner.vue
packages/vue3/src/components/Spinner/types.ts
packages/vue3/src/components/Status/EditableStatus.vue
packages/vue3/src/components/Status/StaticStatus.vue
packages/vue3/src/components/Status/types.ts

Added custom types for slider spinner and status props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Table/Internal/Button.vue
packages/vue3/src/components/Table/Internal/Link.vue
packages/vue3/src/components/Table/Internal/TableRow.vue
packages/vue3/src/components/Table/Internal/types.ts
packages/vue3/src/components/Table/Table.vue
packages/vue3/src/components/Table/types.ts
packages/vue3/src/components/Tag/Tag.vue
packages/vue3/src/components/Tag/TagItem.vue
packages/vue3/src/components/Tag/types.ts

Added custom types for table and tag props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Tabs/Tab.vue
packages/vue3/src/components/Tabs/types.ts
packages/vue3/src/components/TextArea/TextArea.vue
packages/vue3/src/components/TextArea/types.ts
packages/vue3/src/components/Thumbnail/Thumbnail.vue
packages/vue3/src/components/Thumbnail/types.ts

Added custom types for tabs textarea and thumbnail props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Toast/Toast.vue
packages/vue3/src/components/Toast/types.ts
packages/vue3/src/components/Toggle/Toggle.vue
packages/vue3/src/components/Toggle/types.ts
packages/vue3/src/components/Tooltip/Tooltip.vue
packages/vue3/src/components/Tooltip/types.ts

Added custom types for toast toggle and tooltip props

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Table/Internal/TableRow.vue

[YSHOP2-1259](https://youcanshop.atlassian.net/browse/YSHOP2-1259)
[YSHOP2-1259]: https://youcanshop.atlassian.net/browse/YSHOP2-1259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1259: Table > Add ellipsis to cell text

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Dropdown/DropdownList.vue
packages/vue3/src/components/Input/Input.vue
packages/vue3/src/components/Input/types.ts
packages/vue3/src/components/TextArea/TextArea.vue

[YSHOP2-1275](https://youcanshop.atlassian.net/browse/YSHOP2-1275)
[YSHOP2-1275]: https://youcanshop.atlassian.net/browse/YSHOP2-1275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1275: Dropdwon > background color issue

---

package.json
packages/core/package.json
packages/eslint-all/package.json
packages/eslint-basic/package.json
packages/eslint-plugin-youcan/package.json
packages/eslint-typescript/package.json
packages/eslint-vue/package.json
packages/icons/package.json
packages/visuals/package.json
packages/vue3/package.json
packages/vue3/src/components/ToastContainer/ToastContainer.vue

[DOT-X](https://youcanshop.atlassian.net/browse/DOT-X)

Dark fix toast

---

packages/vue3/src/components/Upload/UploadedFile.vue
packages/vue3/src/components/Upload/UploadedMedia.vue
packages/vue3/src/components/Upload/types.ts

[DOT-X](https://youcanshop.atlassian.net/browse/DOT-X)

DARK fix uploadedFile props type lint error

---

packages/vue3/package.json
pnpm-lock.yaml

[YSHOP2-1241](https://youcanshop.atlassian.net/browse/YSHOP2-1241)
[YSHOP2-1241]: https://youcanshop.atlassian.net/browse/YSHOP2-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1241: Upgraded vue and vite versions

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Dropdown/Dropdown.vue
packages/vue3/src/components/Dropdown/MultiselectDropdown.vue
packages/vue3/src/components/Dropdown/types.ts

[YSHOP2-1297](https://youcanshop.atlassian.net/browse/YSHOP2-1297)
[YSHOP2-1297]: https://youcanshop.atlassian.net/browse/YSHOP2-1297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1297: Dropdown > Doesn't have an error state

---

packages/vue3/src/components/DropdownMenu/DropdownMenuItem.vue

Dark: Fixed import error

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Tag/Tag.vue

Tag > Disabled state still allows user to edit

---

packages/vue3/src/env.d.ts
packages/vue3/tsconfig.json

DARK dark-remove-ts-declaration

---

packages/vue3/package.json
packages/vue3/src/components/ToastContainer/ToastContainer.vue
packages/vue3/src/components/ToastContainer/internal/Toast.vue
packages/vue3/src/components/ToastContainer/types.ts
packages/vue3/src/components/index.ts
packages/vue3/src/helpers/index.ts
packages/vue3/src/types/index.ts

Reverts youcan-shop/youcan-ui#266

Revert "DARK: remove any trace of ToastContainer"

---

.eslintrc.js
package.json
pnpm-lock.yaml

Update ESLint config after its removal

DARK: Update ESLint config

---

.eslintrc.js

DARK: fix eslint

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Dropdown/DropdownList.vue
packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
packages/vue3/src/components/Tag/Tag.vue
packages/vue3/src/components/Tag/types.ts
packages/vue3/src/components/ToastContainer/ToastContainer.vue

[YSHOP2-1366](https://youcanshop.atlassian.net/browse/YSHOP2-1366)
[YSHOP2-1366]: https://youcanshop.atlassian.net/browse/YSHOP2-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

YSHOP2-1366: Dropdown Tag component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Dropdown/DropdownList.vue
packages/vue3/src/components/Dropdown/Internal/DropdownItem.vue
packages/vue3/src/components/Tag/Tag.vue

[UI-234](https://youcanshop.atlassian.net/browse/UI-234)
[UI-234]: https://youcanshop.atlassian.net/browse/UI-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-234: Dropdown > auto close on select

---

.github/pull_request_template.md

[UI-246](https://youcanshop.atlassian.net/browse/UI-246)
[UI-246]: https://youcanshop.atlassian.net/browse/UI-246?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-246: Update PR Template to improve QR Steps

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Alert/Alert.vue
packages/vue3/src/components/ToastContainer/ToastContainer.vue
packages/vue3/src/components/ToastContainer/internal/Toast.vue
packages/vue3/src/components/ToastContainer/types.ts

[UI-X](https://youcanshop.atlassian.net/browse/UI-X)

UI-280: ToastContainer > Improvement

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Input/InputGroup.vue

[UI-253](https://youcanshop.atlassian.net/browse/UI-253)
[UI-253]: https://youcanshop.atlassian.net/browse/UI-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

InputGroup > Improvement

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Note/Note.vue

[UI-249](https://youcanshop.atlassian.net/browse/UI-249)
[UI-249]: https://youcanshop.atlassian.net/browse/UI-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Note > Improvement and bug fixes

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Skeleton/Skeleton.vue

[UI-293](https://youcanshop.atlassian.net/browse/UI-293)
[UI-293]: https://youcanshop.atlassian.net/browse/UI-293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-293 > Improved skeleton component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Skeleton/Skeleton.vue
packages/vue3/src/components/Skeleton/types.ts

[UI-301](https://youcanshop.atlassian.net/browse/UI-301)
[UI-301]: https://youcanshop.atlassian.net/browse/UI-301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-301 : Added card skeleton

---

packages/vue3/src/components/Modal/Modal.vue
packages/vue3/src/components/Overlay/Overlay.vue

[UI-289](https://youcanshop.atlassian.net/browse/UI-289)
[UI-289]: https://youcanshop.atlassian.net/browse/UI-289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-289: Modal > Improvement

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Badge/Badge.vue

[UI-267](https://youcanshop.atlassian.net/browse/UI-267)
[UI-267]: https://youcanshop.atlassian.net/browse/UI-267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-267: Small improvement in the component style

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Thumbnail/Thumbnail.vue

[UI-268](https://youcanshop.atlassian.net/browse/UI-268)
[UI-268]: https://youcanshop.atlassian.net/browse/UI-268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-268 : improved thumbnail component

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Drawer/Drawer.vue
packages/vue3/src/components/Drawer/types.ts

[UI-296](https://youcanshop.atlassian.net/browse/UI-296)
[UI-296]: https://youcanshop.atlassian.net/browse/UI-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI 296: Drawer > Improvement

---

packages/vue3/src/components/TextArea/TextArea.vue

[UI-265](https://youcanshop.atlassian.net/browse/UI-265)
[UI-265]: https://youcanshop.atlassian.net/browse/UI-265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-265: TextArea > Improvement

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/Draggable/Draggable.vue
packages/vue3/src/components/Draggable/DraggableItem.vue

[UI-298](https://youcanshop.atlassian.net/browse/UI-298)
[UI-298]: https://youcanshop.atlassian.net/browse/UI-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-298 : Draggable component improved

---

packages/vue3/src/components/Slider/Internal/Rail.vue

[UI-X](https://youcanshop.atlassian.net/browse/UI-X)

fix document is not defined

---

packages/vue3/src/components/Slider/Internal/Rail.vue

This reverts commit 3044d678c96ddafae2d31b2c63c8c4aecd0b0b64.
[UI-X](https://youcanshop.atlassian.net/browse/UI-X)

Revert "fix document is not defined (#308)"

---

packages/phoenix/src/components/Alert/Alert.vue

[UI-278](https://youcanshop.atlassian.net/browse/UI-278)
[UI-278]: https://youcanshop.atlassian.net/browse/UI-278?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-278: Alert > Improvement

---

packages/phoenix/src/_dev/App.vue
packages/phoenix/src/components/Increment/Increment.vue
packages/phoenix/src/components/Increment/types.ts

[UI-269(https://youcanshop.atlassian.net/browse/UI-269)

UI-269: Increment > Improvement

---

packages/phoenix/src/components/Tabs/Tab.stories.ts
packages/phoenix/src/components/Tabs/Tab.vue
packages/phoenix/src/components/Tabs/TabsBar.stories.ts
packages/phoenix/src/components/Tabs/types.ts

[UI-273](https://youcanshop.atlassian.net/browse/UI-273)
[UI-273]: https://youcanshop.atlassian.net/browse/UI-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-273: Tabs > Improvement

---

packages/phoenix/src/components/Spinner/Spinner.stories.ts
packages/phoenix/src/components/Spinner/Spinner.vue
packages/phoenix/src/components/Spinner/types.ts

[UI-294](https://youcanshop.atlassian.net/browse/UI-294)
You can test component in [StoryBook](http://localhost:6007/?path=/story/application-spinner--default) 
[UI-294]: https://youcanshop.atlassian.net/browse/UI-294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-294: Spinner > Improvement

---

packages/phoenix/src/components/Radio/Internal/Radio.vue
packages/phoenix/src/components/Radio/RadioGroup.vue
packages/phoenix/src/components/Status/Status.vue
packages/phoenix/src/components/index.ts
packages/phoenix/src/types/index.ts

[UI-286](https://youcanshop.atlassian.net/browse/UI-286)
[UI-286]: https://youcanshop.atlassian.net/browse/UI-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-286: Radio > Improvement

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/RichText/RichText.vue

[UI-323](https://youcanshop.atlassian.net/browse/UI-323)
[UI-323]: https://youcanshop.atlassian.net/browse/UI-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-323: Fixed RichText bugs

---

package.json
packages/core/package.json
packages/icons/package.json
packages/visuals/package.json
packages/vue3/package.json

DARK: restored version

---

packages/vue3/src/components/Upload/FileInput.stories.ts
packages/vue3/src/components/Upload/FileInput.vue
packages/vue3/src/components/Upload/types.ts

[UI-332](https://youcanshop.atlassian.net/browse/UI-332)
[UI-332]: https://youcanshop.atlassian.net/browse/UI-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-332 : Fixed non editable label

---

packages/vue3/src/components/DateInput/DateInput.stories.ts
packages/vue3/src/components/DateInput/DateInput.vue
packages/vue3/src/components/DateInput/SingleDateInput.stories.ts
packages/vue3/src/components/DateInput/SingleDateInput.vue
packages/vue3/src/components/DateInput/types.ts

[UI-339](https://youcanshop.atlassian.net/browse/UI-339)
[UI-339]: https://youcanshop.atlassian.net/browse/UI-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-339: Added Placeholder Prop to DateInput Component

---

packages/phoenix/src/components/Buttons/Button.vue

[UI-333](https://youcanshop.atlassian.net/browse/UI-333)
[UI-333]: https://youcanshop.atlassian.net/browse/UI-333?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-333: Button > button takes 100% width

---

packages/core/tooling/tokens.json
packages/core/tooling/transform.mjs
packages/vue3/src/_dev/App.vue
packages/vue3/src/assets/main.css

[UI-334](https://youcanshop.atlassian.net/browse/UI-334)
[UI-334]: https://youcanshop.atlassian.net/browse/UI-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-334 : Added arabic font support

---

packages/phoenix/src/_dev/App.vue
packages/phoenix/src/components/Buttons/Button.vue
packages/phoenix/src/components/Input/Input.vue
packages/phoenix/src/components/Input/InputGroup.vue
packages/phoenix/src/components/Input/types.ts
packages/phoenix/src/types/index.ts

[UI-321](https://youcanshop.atlassian.net/browse/UI-321)
[UI-321]: https://youcanshop.atlassian.net/browse/UI-321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-321: InputGroup > Refactor

---

packages/vue3/src/components/DateInput/DatePicker.vue

[UI-348](https://youcanshop.atlassian.net/browse/UI-348)
[UI-348]: https://youcanshop.atlassian.net/browse/UI-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-348: DateInput > 1 day range selection error

---

packages/phoenix/src/components/Input/Input.stories.ts
packages/phoenix/src/components/Input/Input.vue
packages/phoenix/src/components/Input/types.ts

[UI-252](https://youcanshop.atlassian.net/browse/UI-252)
[UI-252]: https://youcanshop.atlassian.net/browse/UI-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-252: Input > Improvement

---

packages/phoenix/src/components/Buttons/Button.stories.ts
packages/phoenix/src/components/Buttons/Button.vue
packages/phoenix/src/components/Buttons/types.ts

[UI-350](https://youcanshop.atlassian.net/browse/UI-UI-350)
[UI-350]: https://youcanshop.atlassian.net/browse/UI-350?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-350: Buttons > Fix icon only ratio

---

packages/phoenix/src/_dev/App.vue
packages/phoenix/src/components/Slider/Internal/Rail.vue
packages/phoenix/src/components/Slider/Slider.vue

[UI-352](https://youcanshop.atlassian.net/browse/UI-352)
[UI-352]: https://youcanshop.atlassian.net/browse/UI-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-352: Slider > Add Touch Events to Slider Component

---

packages/alto/src/assets/main.css
packages/alto/src/components/DropdownMenu/DropdownMenu.vue
packages/alto/src/components/RichText/RichText.vue

[UI-355](https://youcanshop.atlassian.net/browse/UI-355)
[UI-355]: https://youcanshop.atlassian.net/browse/UI-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-355 : Synced alto with vue3

---

.github/workflows/chromatic.yml
.github/workflows/storybook-tests.yml
packages/alto/.storybook/main.ts
packages/alto/src/index.ts
pnpm-lock.yaml

Dark : added cache clearing step

---

packages/alto/chromatic.config.json

[UI-336](https://youcanshop.atlassian.net/browse/UI-336)
[UI-336]: https://youcanshop.atlassian.net/browse/UI-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-336: Updated Chromatic config file

---

packages/alto/src/components/index.ts

[UI-372](https://youcanshop.atlassian.net/browse/UI-372)
[UI-372]: https://youcanshop.atlassian.net/browse/UI-372?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-372: added missing export

---

packages/alto/src/components/Buttons/Button.vue
packages/alto/src/components/Buttons/types.ts

[UI-358](https://github.com/youcan-shop/youcan-ui/issues/358)
[UI-358]: https://youcanshop.atlassian.net/browse/UI-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Require href attribute only for links

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Divider/Divider.stories.ts
packages/alto/src/components/Divider/Divider.vue
packages/alto/src/components/Divider/types.ts

[UI-365](https://youcanshop.atlassian.net/browse/UI-365)
[UI-365]: https://youcanshop.atlassian.net/browse/UI-365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-365: Improved Divider dashed style

---

packages/alto/src/components/ResourcePicker/Internal/Resource.vue
packages/alto/src/components/Skeleton/Skeleton.vue

[UI-371](https://youcanshop.atlassian.net/browse/UI-371)
[UI-371]: https://youcanshop.atlassian.net/browse/UI-371?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-371: changed start to flex-start

---

packages/alto/src/components/Upload/UploadPreview.vue
packages/vue3/src/components/Upload/UploadedMedia.vue

Dark: removed .jpg

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/DatePicker/DatePicker.vue

[UI-377](https://youcanshop.atlassian.net/browse/UI-377)
[UI-377]: https://youcanshop.atlassian.net/browse/UI-377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-377: Hide calendar when user begins scrolling

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Color/ColorInput.vue

[UI-393](https://youcanshop.atlassian.net/browse/UI-393)
[UI-393]: https://youcanshop.atlassian.net/browse/UI-393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-393: Fixed color input scroll

---

packages/vue3/src/components/ResourcePicker/Internal/Resource.vue
packages/vue3/src/components/Skeleton/Skeleton.vue
packages/vue3/src/components/Table/Table.vue

Dark: changes start to flex-start

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Dropdown/Dropdown.vue

[UI-394](https://youcanshop.atlassian.net/browse/UI-394)
[UI-394]: https://youcanshop.atlassian.net/browse/UI-394?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-394: Hiding the dropdown list when the user begins scrolling.

---

bump.config.ts
package.json
pnpm-lock.yaml

Dark: Updated bumpp version and added new config

---

packages/vue3/src/components/Table/Table.vue

Dark: added ts expect error

---

packages/alto/src/components/ResourcePicker/Internal/Resource.vue

[UI-368](https://youcanshop.atlassian.net/browse/UI-368)
[UI-368]: https://youcanshop.atlassian.net/browse/UI-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-368: Removed price for resource with variants

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Status/EditableStatus.stories.ts
packages/alto/src/components/Status/Status.vue
packages/alto/src/components/Status/types.ts

[UI-410](https://youcanshop.atlassian.net/browse/UI-410)
[UI-410]: https://youcanshop.atlassian.net/browse/UI-410?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-410: Status > remove editable prop

---

.github/workflows/storybook-tests.yml

Dark: Fixed playwrite installation command

---

packages/alto/src/components/DatePicker/DatePicker.stories.ts
packages/alto/src/components/DatePicker/DatePickerPresets.stories.ts
packages/alto/src/components/DatePicker/DatePickerRange.stories.ts

[UI-416](https://youcanshop.atlassian.net/browse/UI-416)
[UI-416]: https://youcanshop.atlassian.net/browse/UI-416?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-416: Added story to DatePicker

---

packages/alto/src/components/Table/Table.stories.ts

[UI-417](https://youcanshop.atlassian.net/browse/UI-417)
[UI-417]: https://youcanshop.atlassian.net/browse/UI-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-417: Added story to Table

---

packages/alto/src/components/Progress/Progress.stories.ts
packages/alto/src/components/Progress/Progress.vue
packages/alto/src/components/Progress/types.ts

[UI-419](https://youcanshop.atlassian.net/browse/UI-419)
[UI-418]: https://youcanshop.atlassian.net/browse/UI-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[UI-419]: https://youcanshop.atlassian.net/browse/UI-419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-419: Added story to Progress

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Accordion/Accordion.stories.ts
packages/alto/src/components/Accordion/Accordion.vue
packages/alto/src/components/Accordion/AccordionItem.stories.ts
packages/alto/src/components/Accordion/AccordionItem.vue
packages/alto/src/components/Accordion/types.ts
packages/alto/src/components/index.ts
packages/alto/src/types/index.ts

[UI-423](https://youcanshop.atlassian.net/browse/UI-423)
[UI-423]: https://youcanshop.atlassian.net/browse/UI-423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-423: Added Accordion component

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Avatar/Avatar.stories.ts
packages/alto/src/components/Avatar/Avatar.vue
packages/alto/src/components/Avatar/types.ts
packages/alto/src/components/index.ts
packages/alto/src/types/index.ts

[UI-415](https://youcanshop.atlassian.net/browse/UI-415)
[UI-415]: https://youcanshop.atlassian.net/browse/UI-415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-415: Added Avatar component

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Breadcrumbs/BreadcrumbItem.vue
packages/alto/src/components/Breadcrumbs/Breadcrumbs.stories.ts
packages/alto/src/components/Breadcrumbs/Breadcrumbs.vue
packages/alto/src/components/Breadcrumbs/types.ts
packages/alto/src/components/index.ts
packages/alto/src/types/index.ts

[UI-424](https://youcanshop.atlassian.net/browse/UI-424)
[UI-424]: https://youcanshop.atlassian.net/browse/UI-424?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI 424: Added Breadcrumbs component

---

packages/alto/package.json
packages/alto/src/types/index.ts
packages/vue3/package.json
packages/vue3/src/_dev/App.vue
pnpm-lock.yaml

[UI-396](https://youcanshop.atlassian.net/browse/UI-396)
[UI-396]: https://youcanshop.atlassian.net/browse/UI-396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-396: updated some packages to fix vulnerabilities

---

packages/alto/src/components/RichText/internal/handlers.ts
packages/alto/src/components/RichText/utils.ts
packages/vue3/src/components/RichText/internal/handlers.ts
packages/vue3/src/components/RichText/utils.ts

Dark : fixed types in Richtext

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Breadcrumbs/Breadcrumbs.vue

[UI-453](https://youcanshop.atlassian.net/browse/UI-453)
[UI-453]: https://youcanshop.atlassian.net/browse/UI-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-453: Removed hover on separator

---

packages/alto/src/components/DatePicker/Internal/YearsAndMonths.vue

[UI-445](https://youcanshop.atlassian.net/browse/UI-445)
[UI-445]: https://youcanshop.atlassian.net/browse/UI-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-445: Added Click on year/month to cancel

---

packages/styles/package-lock.json
packages/styles/package.json
packages/styles/postcss.config.js
packages/styles/src/scss/index.scss
pnpm-lock.yaml

[UI-458](https://youcanshop.atlassian.net/browse/UI-458)
[UI-458]: https://youcanshop.atlassian.net/browse/UI-458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-458: Added style package to packages

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/RichText/RichText.vue
packages/vue3/src/components/RichText/RichText.vue

[UI-461](https://youcanshop.atlassian.net/browse/UI-461)
[UI-461]: https://youcanshop.atlassian.net/browse/UI-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-461: Fixed redundent border in RichText

---

.github/workflows/chromatic.yml

[UI-335](https://youcanshop.atlassian.net/browse/UI-335)
[UI-335]: https://youcanshop.atlassian.net/browse/UI-335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-335 : Addded chromatic links comment

---

.eslintignore
.github/pull_request_template.md
.stylelintignore
packages/alto/package.json
packages/alto/src/assets/index.ts
packages/alto/src/components/Buttons/ActionButton.vue
packages/alto/src/components/Buttons/Button.stories.ts
packages/alto/src/components/Buttons/Button.vue
packages/alto/src/index.ts
packages/styles/package.json
packages/styles/src/css/action-button.css
packages/styles/src/css/button.css
packages/styles/src/css/index.css
packages/styles/src/scss/components/action-button.scss
packages/styles/src/scss/components/button.scss
packages/styles/src/scss/index.scss
pnpm-lock.yaml

[UI-460](https://youcanshop.atlassian.net/browse/UI-460)
[UI-460]: https://youcanshop.atlassian.net/browse/UI-460?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-460: Extracting button styles

---

packages/vue3/src/_dev/App.vue
packages/vue3/src/components/RichText/RichText.vue
packages/vue3/src/components/RichText/types.ts
packages/vue3/src/types/index.ts

[UI-470](https://youcanshop.atlassian.net/browse/UI-470)
[UI-470]: https://youcanshop.atlassian.net/browse/UI-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-470: Added text alignment prop to RichText component

---

.github/workflows/chromatic.yml

Dark: Updated chromatic workflow

---

.vscode/settings.json
packages/alto/src/components/Avatar/Avatar.vue
packages/styles/package.json
packages/styles/src/css/avatar.css
packages/styles/src/css/button.css
packages/styles/src/css/index.css
packages/styles/src/scss/components/avatar.scss
packages/styles/src/scss/components/button.scss

[UI-464](https://youcanshop.atlassian.net/browse/UI-464)
[UI-464]: https://youcanshop.atlassian.net/browse/UI-464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-464: Avatar Component Style Extraction

---

packages/alto/src/components/Alert/Alert.vue
packages/styles/package.json
packages/styles/src/css/alert.css
packages/styles/src/scss/components/alert.scss

[UI-463](https://youcanshop.atlassian.net/browse/UI-463)
[UI-463]: https://youcanshop.atlassian.net/browse/UI-463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-463: Extracted Alert style

---

packages/alto/src/components/Badge/Badge.vue
packages/styles/package.json
packages/styles/src/css/badge.css
packages/styles/src/scss/components/badge.scss

[UI-465](https://youcanshop.atlassian.net/browse/UI-465)
[UI-465]: https://youcanshop.atlassian.net/browse/UI-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-465: Extracted badge style

---

packages/alto/src/components/Checkbox/Checkbox.vue
packages/styles/package.json
packages/styles/src/css/checkbox.css
packages/styles/src/scss/components/checkbox.scss

[UI-468](https://youcanshop.atlassian.net/browse/UI-468)
[UI-468]: https://youcanshop.atlassian.net/browse/UI-468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-468: Checkbox Component Style Extraction

---

packages/alto/src/components/Radio/Internal/Radio.vue
packages/alto/src/components/Radio/RadioGroup.vue
packages/styles/package.json
packages/styles/src/css/radio-group.css
packages/styles/src/scss/components/radio-group.scss

[UI-474](https://youcanshop.atlassian.net/browse/UI-474)
[UI-474]: https://youcanshop.atlassian.net/browse/UI-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-474: Extracted RadioGroup style component

---

.stylelintrc.json
packages/alto/src/components/Loader/Loader.vue
packages/alto/src/components/Loader/internal/Bar.vue
packages/alto/src/components/Loader/internal/Brand.vue
packages/alto/src/components/Loader/internal/Spinner.vue
packages/styles/package.json
packages/styles/src/css/loader.css
packages/styles/src/scss/components/loader.scss

[UI-473](https://youcanshop.atlassian.net/browse/UI-473)
[UI-473]: https://youcanshop.atlassian.net/browse/UI-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-473: Extracted lLoader style component

---

.stylelintrc.json
packages/alto/src/components/RadioList/RadioList.vue
packages/styles/package.json
packages/styles/src/css/index.css
packages/styles/src/css/radio-list.css
packages/styles/src/scss/components/radio-list.scss
packages/styles/src/scss/index.scss

[UI-476](https://youcanshop.atlassian.net/browse/UI-476)
[UI-476]: https://youcanshop.atlassian.net/browse/UI-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-476: Extracted RadioList style component

---

.stylelintrc.json
packages/alto/src/components/Divider/Divider.vue
packages/styles/package.json
packages/styles/src/css/divider.css
packages/styles/src/scss/components/divider.scss

[UI-472](https://youcanshop.atlassian.net/browse/UI-472)
[UI-472]: https://youcanshop.atlassian.net/browse/UI-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-472: Extracted Divider style component

---

.stylelintrc.json
packages/alto/src/_dev/App.vue
packages/alto/src/components/Note/Note.vue
packages/styles/package.json
packages/styles/src/css/note.css
packages/styles/src/scss/components/note.scss

[UI-475](https://youcanshop.atlassian.net/browse/UI-475)
[UI-475]: https://youcanshop.atlassian.net/browse/UI-475?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-475: Extracted Note style component

---

.stylelintrc.json
packages/alto/src/components/Rating/Rating.vue
packages/styles/package.json
packages/styles/src/css/index.css
packages/styles/src/css/rating.css
packages/styles/src/scss/components/rating.scss
packages/styles/src/scss/index.scss

[UI-477X](https://youcanshop.atlassian.net/browse/UI-477)

UI-477: Extracted Rating style component

---

packages/alto/src/_dev/App.vue
packages/alto/src/components/Breadcrumbs/BreadcrumbItem.vue
packages/alto/src/components/Breadcrumbs/Breadcrumbs.vue
packages/styles/package.json
packages/styles/src/css/breadcrumbs.css
packages/styles/src/css/index.css
packages/styles/src/scss/components/breadcrumbs.scss
packages/styles/src/scss/index.scss

[UI-466](https://youcanshop.atlassian.net/browse/UI-466)
[UI-466]: https://youcanshop.atlassian.net/browse/UI-466?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-466: Extracted Breadcrumbs style component

---

.gitignore
packages/alto/src/_dev/App.vue
packages/alto/src/components/Thumbnail/Thumbnail.vue
packages/styles/package.json
packages/styles/src/css/index.css
packages/styles/src/css/thumbnail.css
packages/styles/src/scss/components/thumbnail.scss
packages/styles/src/scss/index.scss

[UI-X](https://youcanshop.atlassian.net/browse/UI-X)

UI-481: Extracted Thumbnail style component

---

packages/alto/src/components/Toggle/Toggle.vue
packages/styles/package.json
packages/styles/src/css/index.css
packages/styles/src/css/toggle.css
packages/styles/src/scss/components/toggle.scss
packages/styles/src/scss/index.scss

[UI-482](https://youcanshop.atlassian.net/browse/UI-482)
[UI-482]: https://youcanshop.atlassian.net/browse/UI-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-482: Extracted Toggle component styles

---

packages/alto/src/components/Tooltip/Tooltip.vue
packages/styles/package.json
packages/styles/src/css/index.css
packages/styles/src/css/tooltip.css
packages/styles/src/scss/components/tooltip.scss
packages/styles/src/scss/index.scss

[UI-483](https://youcanshop.atlassian.net/browse/UI-483)
[UI-483]: https://youcanshop.atlassian.net/browse/UI-483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

UI-483 : Extracted Tooltip component styles
